### PR TITLE
chore(dev): add migration entries and export hostConfig types correctly

### LINKED ISSUE #2826: fix(ext-bridge, remote-core): published types import the private, unpublished @mittwald/flow-core
The published type declarations of `@mittwald/ext-bridge` and `@mittwald/flow-remote-core` import `HostConfig` from `@mittwald/flow-core` — a **private package that is never published** (`npm view @mittwald/flow-core` → 404). Consumers cannot install it, so their TypeScript build fails.

Runtime is unaffected: only sourcemaps reference the package, no emitted `.mjs` imports it. This is a types-only break, but it hits every TypeScript consumer of either package.

## Reproduction

```bash
mkdir /tmp/repro && cd /tmp/repro && npm init -y
npm i @mittwald/ext-bridge@0.2.0-alpha.1018
printf 'import type { ExtBridgeConfig } from "@mittwald/ext-bridge";\nexport const f = (c: ExtBridgeConfig) => c.sessionId;\n' > index.ts
npx tsc --noEmit --strict --moduleResolution bundler --module esnext index.ts
```

```
node_modules/@mittwald/ext-bridge/dist/types/config/types.d.ts(3,28):
  error TS2307: Cannot find module '@mittwald/flow-core' or its corresponding type declarations.
```

With `skipLibCheck: true` the error is silenced and the failure gets worse, because it becomes invisible: `ExtBridgeConfig` degrades to `any`. This compiles clean under `--strict --skipLibCheck`:

```ts
import type { ExtBridgeConfig } from "@mittwald/ext-bridge";
type Probe = ExtBridgeConfig["nonExistentField"]; // no error — the type is `any`
export const p: Probe = 123;
```

So `sessionId`, `userId`, `extensionId`, `projectId` and friends silently lose all type safety.

## Affected versions

First published version: **`0.2.0-alpha.789`** (`0.2.0-alpha.788` is clean). Still present in the current `0.2.0-alpha.1018` — roughly four months of releases.

Introduced by 5288973b3 `feat(Remote): auto-set host language on remote-side`.

## Affected files (in the published packages)

`@mittwald/ext-bridge`
- `dist/types/config/types.d.ts` — `ExtBridgeConfig`, `ExtBridgeConfigInput`
- `dist/types/config/extractHostConfig.d.ts`

`@mittwald/flow-remote-core`
- `dist/types/connection/types.d.ts` — reaches `HostExports.getHostConfig`
- `dist/types/connection/connectRemoteIframe.d.ts`
- `dist/types/ext-bridge/getWithMergedHostConfig.d.ts`

## Root cause

`@mittwald/flow-core` is a `devDependency` of both packages, but `HostConfig` appears in **public** type signatures:

```ts
// packages/ext-bridge/src/config/types.ts
import type { HostConfig } from "@mittwald/flow-core";
export type ExtBridgeConfig = z.infer<typeof config> & HostConfig;
```

A devDependency may not appear in emitted `.d.ts`. Inside the workspace the import resolves through the workspace link, so `test:compile` passes and the leak is invisible in CI. It only surfaces after installing from the registry — which nothing in CI does.

## Possible fixes

1. Move `HostConfig` into a published package (`ext-bridge` is the natural home; `remote-core` already has `@mittwald/ext-bridge` as a peer dependency) and import it from there.
2. Publish `@mittwald/flow-core`.
3. Inline the type in both packages.

Option 1 keeps a single source of truth without adding a package to the public surface.

## Suggested guard

The class of bug — a published `.d.ts` referencing something consumers cannot resolve — is worth a CI check, otherwise it recurs. Either:

- install the packed tarballs into a clean directory and run `tsc` against a tiny consumer file, or
- run [`@arethetypeswrong/cli`](https://github.com/arethetypeswrong/arethetypeswrong.github.io) over the packed tarballs.

Both catch it; neither needs a published release to run.

---

Found while auditing the published API surface of `@mittwald/flow-remote-react-components`, `@mittwald/flow-remote-core` and `@mittwald/ext-bridge` for breaking changes since 2026-01-01. The full breaking-change inventory from that audit follows in a comment.

### PR DESCRIPTION
**Pull request by ins0**
related https://github.com/mittwald/flow/issues/2825
fixes https://github.com/mittwald/flow/issues/2826

### CODE REVIEW

File: packages/core/src/index.ts [hunk 1]
```diff
@@ -1 +1 @@
-export * from "./remote/types";
+export {};
```
Comment (Lisa18289) [inline packages/core/src/index.ts:1]: kann das nicht ganz weg wenn es nur noch `{}` exportiert?

File: packages/codemods/src/transforms/flowAlphaColorPrimaryToDefault.ts [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+ * The scope is deliberately narrow. Only JSX elements that resolve to one of
+ * those components — imported (named or as a namespace) from
+ * `@mittwald/flow-react-components` or
+ * `@mittwald/flow-remote-react-components`, including their subpath entries —
+ * are touched. Components that still accept `color="primary"` (e.g. `Button`)
+ * and same-named elements from other packages (e.g. a router `Link`) are left
+ * untouched. Only the literal value `"primary"` is rewritten (`color="primary"`
+ * and `color={"primary"}`); dynamic values such as `color={expr}` are skipped.
+ */
+const flowAlphaColorPrimaryToDefaultTransform: Transform = (
```
Comment (Lisa18289) [inline packages/codemods/src/transforms/flowAlphaColorPrimaryToDefault.ts:17]: ich weiß nicht obs das wirklich braucht, primary war eh der default, daher dürfte das eigentlich kaum gesetzt worden sein

**Review by Lisa18289 — APPROVED** [review]
